### ISSUE TITLE
Complete Message: 'Operator' object has no attribute 'no_diff_in'

### ISSUE THREAD

**Issue by lamoni** [Juniper/jsnapy#342]
### Description of Issue/Question
I converted an old jsnap test file to jsnapy yaml file with jsnap2py, and one of the test operators  (no_diff_in) is either named incorrectly, or doesn't exist.

```
Complete Message: 'Operator' object has no attribute 'no_diff_in'
```

**Comment by dmontagner** [comment]
no-diff-in should be translated to no-diff with a ignore-null attribute set to True.

See here:

https://github.com/Juniper/jsnapy/pull/168


Diogo Montagner
APAC CoE
Juniper Networks

**Comment by lamoni** [comment]
Thanks @dmontagner! 

What does ignore-null actually do?

**Comment by dmontagner** [comment]
Same thing than no-diff-in in the old JSNAP.

If you are doing a no-diff in a scenario like below:


pre-snapshot:

<a>
  <b>
    <c>
    </c>
  </b>
  <b>
  </b>
  <b>
  </b>
</a>

post-snapshot:

<a>
  <b>
    <c>
    </c>
  </b>
  <b>
  </b>
  <b>
  </b>
</a>

If you are doing a no-diff between the snapshots above on the xpath /a/b/c, it will fail because <c> does not exist on the other two /a/b entries. That’s where the ignore-null comes into play.

This scenario is usually found under the /chassis sub-tree.

**Comment by lamoni** [comment]
Excellent, thanks. I'll close for now. Will probably submit pull request for handling this automatically.
